const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("terminator", {
  createTerminal: (cwd) => ipcRenderer.invoke("create-terminal", cwd),
  sendInput: (id, data) => ipcRenderer.send("terminal-input", id, data),
  resize: (id, cols, rows) => ipcRenderer.send("terminal-resize", id, cols, rows),
  kill: (id) => ipcRenderer.send("terminal-kill", id),
  broadcast: (ids, data) => ipcRenderer.send("terminal-broadcast", ids, data),
  getCwd: (id) => ipcRenderer.invoke("get-terminal-cwd", id),
  getProcess: (id) => ipcRenderer.invoke("get-terminal-process", id),
  getGitBranch: (dir) => ipcRenderer.invoke("get-git-branch", dir),
  getGitStatus: (dir) => ipcRenderer.invoke("get-git-status", dir),
  toggleFullscreen: () => ipcRenderer.send("toggle-fullscreen"),
  quit: () => ipcRenderer.send("quit-app"),
  notify: (title, body) => ipcRenderer.send("show-notification", title, body),
  openInEditor: (filePath) => ipcRenderer.send("open-in-editor", filePath),
  saveSession: (data) => ipcRenderer.send("save-session", data),
  loadSession: () => ipcRenderer.invoke("load-session"),
  saveConfig: (config) => ipcRenderer.send("save-config", config),
  loadConfig: () => ipcRenderer.invoke("load-config"),
  saveSnippets: (data) => ipcRenderer.send("save-snippets", data),
  loadSnippets: () => ipcRenderer.invoke("load-snippets"),
  saveProfiles: (data) => ipcRenderer.send("save-profiles", data),
  loadProfiles: () => ipcRenderer.invoke("load-profiles"),
  saveRecents: (data) => ipcRenderer.send("save-recents", data),
  loadRecents: () => ipcRenderer.invoke("load-recents"),
  cronList: () => ipcRenderer.invoke("cron-list"),
  cronAdd: (line) => ipcRenderer.invoke("cron-add", line),
  cronRemove: (index) => ipcRenderer.invoke("cron-remove", index),
  findFiles: (query, dirs) => ipcRenderer.invoke("find-files", query, dirs),
  saveOutput: (content, name) => ipcRenderer.invoke("save-output", content, name),
  // New features
  systemStats: () => ipcRenderer.invoke("system-stats"),
  saveSsh: (data) => ipcRenderer.send("save-ssh", data),
  loadSsh: () => ipcRenderer.invoke("load-ssh"),
  saveNotes: (data) => ipcRenderer.send("save-notes", data),
  loadNotes: () => ipcRenderer.invoke("load-notes"),
  logAppend: (paneId, data) => ipcRenderer.send("log-append", paneId, data),
  getLogPath: (paneId) => ipcRenderer.invoke("get-log-path", paneId),
  dockerPs: () => ipcRenderer.invoke("docker-ps"),
  dockerPsAll: () => ipcRenderer.invoke("docker-ps-all"),
  getTerminalEnv: (id) => ipcRenderer.invoke("get-terminal-env", id),
  readFile: (filePath, maxBytes) => ipcRenderer.invoke("read-file", filePath, maxBytes),
  saveBookmarks: (data) => ipcRenderer.send("save-bookmarks", data),
  loadBookmarks: () => ipcRenderer.invoke("load-bookmarks"),
  getProcessTree: (id) => ipcRenderer.invoke("get-process-tree", id),
  onData: (callback) => ipcRenderer.on("terminal-data", (_, id, data) => callback(id, data)),
  onExit: (callback) => ipcRenderer.on("terminal-exit", (_, id, exitCode) => callback(id, exitCode)),
});
