const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("terminator", {
  createTerminal: (cwd) => ipcRenderer.invoke("create-terminal", cwd),
  sendInput: (id, data) => ipcRenderer.send("terminal-input", id, data),
  resize: (id, cols, rows) => ipcRenderer.send("terminal-resize", id, cols, rows),
  kill: (id) => ipcRenderer.send("terminal-kill", id),
  broadcast: (ids, data) => ipcRenderer.send("terminal-broadcast", ids, data),
  getCwd: (id) => ipcRenderer.invoke("get-terminal-cwd", id),
  getProcess: (id) => ipcRenderer.invoke("get-terminal-process", id),
  getGitBranch: (dir) => ipcRenderer.invoke("get-git-branch", dir),
  getGitStatus: (dir) => ipcRenderer.invoke("get-git-status", dir),
  toggleFullscreen: () => ipcRenderer.send("toggle-fullscreen"),
  quit: () => ipcRenderer.send("quit-app"),
  notify: (title, body) => ipcRenderer.send("show-notification", title, body),
  openInEditor: (filePath) => ipcRenderer.send("open-in-editor", filePath),
  saveSession: (data) => ipcRenderer.send("save-session", data),
  loadSession: () => ipcRenderer.invoke("load-session"),
  saveConfig: (config) => ipcRenderer.send("save-config", config),
  loadConfig: () => ipcRenderer.invoke("load-config"),
  saveSnippets: (data) => ipcRenderer.send("save-snippets", data),
  loadSnippets: () => ipcRenderer.invoke("load-snippets"),
  saveProfiles: (data) => ipcRenderer.send("save-profiles", data),
  loadProfiles: () => ipcRenderer.invoke("load-profiles"),
  saveRecents: (data) => ipcRenderer.send("save-recents", data),
  loadRecents: () => ipcRenderer.invoke("load-recents"),
  cronList: () => ipcRenderer.invoke("cron-list"),
  cronAdd: (line) => ipcRenderer.invoke("cron-add", line),
  cronRemove: (index) => ipcRenderer.invoke("cron-remove", index),
  findFiles: (query, dirs) => ipcRenderer.invoke("find-files", query, dirs),
  saveOutput: (content, name) => ipcRenderer.invoke("save-output", content, name),
  // New features
  systemStats: () => ipcRenderer.invoke("system-stats"),
  saveSsh: (data) => ipcRenderer.send("save-ssh", data),
  loadSsh: () => ipcRenderer.invoke("load-ssh"),
  saveNotes: (data) => ipcRenderer.send("save-notes", data),
  loadNotes: () => ipcRenderer.invoke("load-notes"),
  logAppend: (paneId, data) => ipcRenderer.send("log-append", paneId, data),
  getLogPath: (paneId) => ipcRenderer.invoke("get-log-path", paneId),
  dockerPs: () => ipcRenderer.invoke("docker-ps"),
  dockerPsAll: () => ipcRenderer.invoke("docker-ps-all"),
  getTerminalEnv: (id) => ipcRenderer.invoke("get-terminal-env", id),
  readFile: (filePath, maxBytes) => ipcRenderer.invoke("read-file", filePath, maxBytes),
  saveBookmarks: (data) => ipcRenderer.send("save-bookmarks", data),
  loadBookmarks: () => ipcRenderer.invoke("load-bookmarks"),
  saveProjects: (data) => ipcRenderer.send("save-projects", data),
  loadProjects: () => ipcRenderer.invoke("load-projects"),
  getProcessTree: (id) => ipcRenderer.invoke("get-process-tree", id),
  loadSettings: () => ipcRenderer.invoke("load-settings"),
  saveSettings: (data) => ipcRenderer.send("save-settings", data),
  getAppVersion: () => ipcRenderer.invoke("get-app-version"),
  getDefaultShell: () => ipcRenderer.invoke("get-default-shell"),
  checkForUpdates: () => ipcRenderer.invoke("check-for-updates"),
  sshRemoteList: ({ host, user, port, password, remotePath }) =>
    ipcRenderer.invoke("ssh-remote-list", { host, user, port, password, remotePath }),
  sshRemoteOpenAll: ({ host, user, port, password, sessions }) =>
    ipcRenderer.invoke("ssh-remote-open-all", { host, user, port, password, sessions }),
  aiComplete: (params) => ipcRenderer.invoke("ai-complete", params),
  aiChat: (params) => ipcRenderer.invoke("ai-chat", params),
  getPaneStats: (id) => ipcRenderer.invoke("get-pane-stats", id),
  listPorts: () => ipcRenderer.invoke("list-ports"),
  killPort: (pid) => ipcRenderer.invoke("kill-port", pid),
  savePipelines: (data) => ipcRenderer.invoke("save-pipelines", data),
  loadPipelines: () => ipcRenderer.invoke("load-pipelines"),
  execPipelineStep: (params) => ipcRenderer.invoke("exec-pipeline-step", params),
  saveCmdBookmarks: (data) => ipcRenderer.send("save-cmd-bookmarks", data),
  loadCmdBookmarks: () => ipcRenderer.invoke("load-cmd-bookmarks"),
  onData: (callback) => ipcRenderer.on("terminal-data", (_, id, data) => callback(id, data)),
  onExit: (callback) => ipcRenderer.on("terminal-exit", (_, id, exitCode) => callback(id, exitCode)),
  // Plugin system
  loadPlugins: () => ipcRenderer.invoke("load-plugins"),
  getPluginCode: (name) => ipcRenderer.invoke("get-plugin-code", name),
  listAvailablePlugins: () => ipcRenderer.invoke("list-available-plugins"),
  installPlugin: (dir) => ipcRenderer.invoke("install-plugin", dir),
  uninstallPlugin: (dir) => ipcRenderer.invoke("uninstall-plugin", dir),
  // Marketplace
  fetchRegistry: () => ipcRenderer.invoke("fetch-registry"),
  installFromRegistry: (params) => ipcRenderer.invoke("install-from-registry", params),
  // Package install
  installTermext: (filePath) => ipcRenderer.invoke("install-termext", filePath),
  downloadAndInstallTermext: (params) => ipcRenderer.invoke("download-and-install-termext", params),
  pickTermextFile: () => ipcRenderer.invoke("pick-termext-file"),
  onUpdateStatus: (callback) => ipcRenderer.on("update-status", (_, data) => callback(data)),
  // Window controls (Windows/Linux)
  winMinimize: () => ipcRenderer.send("win-minimize"),
  winMaximize: () => ipcRenderer.send("win-maximize"),
  winClose: () => ipcRenderer.send("win-close"),
  platform: process.platform,
  // Secrets manager
  loadSecrets: () => ipcRenderer.invoke("load-secrets"),
  saveSecrets: (data) => ipcRenderer.send("save-secrets", data),
  injectSecrets: (params) => ipcRenderer.invoke("inject-secrets", params),
  // Startup tasks
  saveStartupTasks: (data) => ipcRenderer.send("save-startup-tasks", data),
  loadStartupTasks: () => ipcRenderer.invoke("load-startup-tasks"),
  // Status bar helpers
  getK8sContext: () => ipcRenderer.invoke("get-k8s-context"),
  getAwsProfile: () => ipcRenderer.invoke("get-aws-profile"),
  getNodeVersion: () => ipcRenderer.invoke("get-node-version"),
});
